bills/urls.py
from django.urls                        import path



urlpatterns = [
#    path('status/', StatusView.as_view(), name='status'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^simon/', include('simon.urls')),
    url(r'^wenjian/', include('wenjian.urls')),
    url(r'^bills/', include('bills.urls'))
]

wenjian/urls.py
from django.conf.urls                   import url
from django.urls                        import path

from .                                  import views

from wenjian.views                      import JobList, NewJob, LoginView, LogoutView
from wenjian.views                      import PortList, PortNew, PortUpdate
from wenjian.views                      import CurrencyNew, CurrencyUpdate, CurrencyList
from wenjian.views                      import RoleNew, RoleUpdate, RoleList
from wenjian.views                      import ClientNew, ClientList, ClientRole
from wenjian.views                      import ContactNew, ContactUpdate, ContactList
from wenjian.views                      import ExpenseList, ExpenseNew, ExpenseUpdate
from wenjian.views                      import ContainersizeNew, ContainersizeUpdate, ContainersizeList
from wenjian.views                      import BranchOffice, UpdateOffice, BranchOfficeList
from wenjian.views                      import User, UserList, ChangePassword, UpdateUser
from wenjian.views                      import CntrListView, ContainerView


urlpatterns = [
    url(r'^$',                          views.home,                     name='home'),

    # Login and Logout
    path('login/',                      LoginView.as_view(),            name = 'login'),
    path('logout/',                     views.LogoutView,               name = 'logout'),

    # USER urls
    path('userlist/',                   UserList.as_view(),             name = 'userlist'),
    path('user/',                       User.as_view(),                 name = 'newuser'),
    path('user/<pk>',                   UpdateUser.as_view(),           name = 'updateuser'),
    path('password/<pk>',               ChangePassword.as_view(),       name = 'password'),    

    # Branch Office urls
    path('branchoffice/',               BranchOffice.as_view(),         name = 'newoffice'),
    path('branchoffice/<pk>',           UpdateOffice.as_view(),         name = 'updateoffice'),
    path('officelist/',                 BranchOfficeList.as_view(),     name = 'officelist'),


    # Job Handling url List
    path('joblist/',                    JobList.as_view(),              name = 'joblist'),
    path('job/',                        NewJob.as_view(),               name = 'newjob'),
    path('job/<pk>',                    NewJob.as_view(),               name = 'updatejob'),
    
    path('containerlist/<job_no>',      CntrListView.as_view(),         name = 'containerlist'),
    path('container/<job_no>',          ContainerView.as_view(),        name = 'newcontainer'),
    path('containerupdt/<pk>',          ContainerView.as_view(),        name = 'updatecontainer'),

    # Client url list
    path('client/',                     ClientNew.as_view(),            name = 'client'),
    path('client/<pk>',                 ClientNew.as_view(),            name = 'clientupdate'),
    path('clientlist/<page_id>',        ClientList.as_view(),           name = 'clientlist'),

    # Contact url List
    path('contactlist/<client_id>',     ContactList.as_view(),          name = 'contactlist'),
    path('contactadd/<client_id>',      ContactNew.as_view(),           name = 'contactadd'),
    path('contact/<pk>',                ContactUpdate.as_view(),        name = 'contactupdate'),

    # Client Roles url
    path('clientrole/<client_id>',     ClientRole.as_view(),            name = 'clientrole'),

    # port handling url list
    path('portlist/',                   PortList.as_view(),             name = 'portlist'),
    path('port/',                       PortNew.as_view(),              name = 'port'),
    path('port/<pk>',                   PortUpdate.as_view(),           name = 'portupdate'),

    # currency handling url list
    path('currency/',                   CurrencyNew.as_view(),          name = 'currency'),
    path('currency/<pk>',               CurrencyUpdate.as_view(),       name = 'currency_update'),
    path('currencylist',                CurrencyList.as_view(),         name = 'currencylist'),

    # role handling url list
    path('role/',                       RoleNew.as_view(),              name = 'role'),
    path('role/<pk>',                   RoleUpdate.as_view(),           name = 'roleupdate'),
    path('rolelist/',                   RoleList.as_view(),             name = 'rolelist'),

    # expense handling url list
    path('expense/',                    ExpenseNew.as_view(),           name = 'expense'),
    path('expense/<pk>',                ExpenseUpdate.as_view(),        name = 'expenseupdate'),
    path('expenselist/',                ExpenseList.as_view(),          name = 'expenselist'),

    # ContainerSize handling url list
    path('containersize/',              ContainersizeNew.as_view(),     name = 'containersize'),
    path('containersize/<pk>',          ContainersizeUpdate.as_view(),  name = 'containersizeupdate'),
    path('containersizelist/',          ContainersizeList.as_view(),    name = 'containersizelist'),
]

wenjian/models.py
from django.db import models
from django.urls import reverse
import datetime

from django.contrib.auth.models import Group, User

# Create your models here.

class branch_office(models.Model):
    office_shortcut     = models.CharField( max_length = 50,        verbose_name = "OFFICE SHORTCUT")
    office_name         = models.CharField( max_length = 150,       verbose_name = 'OFFICE NAME', )
    office_address      = models.TextField( max_length = 400,       verbose_name = 'OFFICE ADDRESS',)
    office_ac_code      = models.CharField( max_length = 5,         verbose_name = 'A/C CODE',)
    office_tel          = models.CharField( max_length = 20,        verbose_name = 'OFFICE TELEPHONE',)
    office_code         = models.CharField( max_length = 2,         verbose_name = "OFFICE CODE")
    update_date         = models.DateField(
        auto_now_add    = False,
        auto_now        = False,
        verbose_name    = "UPDATE-DATE",
        blank           = True,
    )
    def __str__(self):
        return self.office_shortcut

    def get_absolute_url(self):
        return reverse('officelist')

class branch_user(User):
    branch_office       = models.ForeignKey(
        'branch_office', 
        on_delete       = models.CASCADE,
        verbose_name    = "BRANCH OFFICE",
    )
    validate_date       = models.DateField(
        auto_now_add    = False,
        auto_now        = False,
        verbose_name    = "VALIDATE TO",
    )

    def __str__(self):
        return str(self.username)

    def get_absolute_url(self):
        return reverse('userlist')

class client(models.Model):
    client_shortcut     = models.CharField(max_length = 30)
    client_name         = models.CharField(max_length = 100)
    client_address      = models.TextField(max_length = 400)
    client_tel          = models.CharField(max_length = 30)
    client_email        = models.EmailField()
    update_date         = models.DateField(
        auto_now_add    = True,
        verbose_name    = "UPDATE DATE",
    )

    def __str__(self):
        return self.client_shortcut

class client_pic(models.Model):
    client              = models.ForeignKey(
        'client', 
        on_delete       = models.CASCADE,
        verbose_name    = 'CLIENT',
    )
    pic_name            = models.CharField(
        max_length=25,
        verbose_name    = "NAME",
    )
    pic_mobile          = models.CharField(
        max_length      = 25,
        verbose_name    = 'MOBILE',
    )
    pic_email           = models.EmailField(
        verbose_name    = 'E-MAIL',
    )
    pic_position        = models.CharField(
        max_length      = 10,
        verbose_name    = 'POSITION',
    )
    update_date         = models.DateField(
        auto_now_add    = True,
        verbose_name    = 'UPDATE DATE',
    )

    def __str__(self):
        return self.pic_name

    def get_absolute_url(self):
        return reverse('contactlist/<client_id>')

class currency(models.Model):
    currency            = models.CharField(
        max_length      = 8, 
        verbose_name    = "CURRENCY",
    )
    exchangerate        = models.DecimalField(
        max_digits      = 4, 
        decimal_places  = 2, 
        verbose_name    = 'EXCHANGE RATE',
    )
    updatedate          = models.DateField(
        auto_now_add    = False,
        auto_now        = False,
        verbose_name    = "UPDATE DATE",
    )
    startdate           = models.DateField(
        auto_now_add    = False,
        auto_now        = False,
        verbose_name    = "START DATE",
    )
    enddate             = models.DateField(
        auto_now_add    = False,
        auto_now        = False,
        verbose_name    = "END DATE",
    )
    update_date         = models.DateField(
        auto_now_add    = False,
        auto_now        = False,
        verbose_name    = "UPDATE-DATE",
        blank           = True,
    )
    def __str__(self):
        return self.currency
    
    
    def get_absolute_url(self):
        return reverse('currencylist')

class port(models.Model):
    port = models.CharField(max_length=50)
    update_date         = models.DateField(
        auto_now_add    = False,
        auto_now        = False,
        verbose_name    = "UPDATE DATE",
        blank           = True,
    )

    def __str__(self):
        return self.port

    def get_absolute_url(self):
        return reverse('portlist')


class job(models.Model):
    status_choice       = (
        ('NORMAL', 'NORMAL'),
        ('FINISHED', 'FINISHED'),
        ('VOIDED', 'VOIDED'),
    )

    job_no              = models.CharField(
        max_length      = 20, 
        verbose_name    = "JOB NO",
        blank           = True
    )
    booking_no          = models.CharField(
        max_length      = 20, 
        verbose_name    = "BOOKING NO", 
        blank           = True,
        null            = True,
    )
    client              = models.ForeignKey(
        'client', 
        on_delete       = models.CASCADE,
        verbose_name    = "CLIENT",
    )
    pol                 = models.ForeignKey(
        'port', 
        on_delete       = models.CASCADE, 
        verbose_name    = "PORT OF LOADING",
        related_name    ='loading',
    )
    pod                 = models.ForeignKey(
        'port', 
        on_delete       = models.CASCADE, 
        verbose_name    = "PORT OF DISCHARGING",
        related_name ='discharge',
    )
    vessel              = models.CharField(
        max_length      = 50, 
        verbose_name    = "VESSEL", 
        blank           = True,
        null            = True,
    )
    pre_carriage        = models.CharField(
        max_length      = 50, 
        verbose_name    = 'PRE-CARRIAGE', 
        blank           = True,
        null            = True,
    )
    doc                 = models.DateField(
        auto_now_add    = False, 
        auto_now        = False, 
        verbose_name    = "CLOSING DATE",
        blank           = True,
        null            = True,
    )
    etd                 = models.DateField(
        auto_now_add    = False, 
        auto_now        = False,
        verbose_name    = 'ESTIMATE DEPARTURE',
        blank           = True,
        null            = True,
    )
    eta                 = models.DateField(
        auto_now_add    = False, 
        auto_now        = False,
        verbose_name    = "ESTIMATE ARRIVAL",
        blank           = True,
        null            = True,
    )
    voyage              = models.CharField(
        max_length      = 50, 
        verbose_name    = "VOYAGE",
        blank           = True,
        null            = True,
    )
    book_agent          = models.ForeignKey(
        'client', 
        on_delete       = models.CASCADE, 
        verbose_name    = 'BOOKING AGENT', 
        related_name    = 'bookingagent',
        blank           = True,
        null            = True,
    )
    carrier             = models.ForeignKey(
        'client', 
        on_delete       = models.CASCADE, 
        verbose_name    = 'CARRIER', 
        related_name    = "shippingline",
        blank           = True,
        null            = True,
    )
    destination_agent   = models.ForeignKey(
        'client', 
        on_delete       = models.CASCADE, 
        verbose_name    = "RELEASE AGENT", 
        related_name    = "releaseagent",
        blank           = True,
        null            = True,
    )
    create_date         = models.DateField(
        auto_now_add    = False, 
        auto_now        = False,
        verbose_name    = 'DATE OF CREATE',
        blank           = True,
    )
    finish_date         = models.DateField(
        auto_now_add    = False, 
        auto_now        = False,
        verbose_name    = "FINISH DATE",
        blank           = True,
        null            = True,
    )
    status              = models.CharField(
        max_length      = 20,
        choices         = status_choice, 
        verbose_name    = 'JOB STATUS',
    )
    place_of_receipt    = models.CharField(
        max_length      = 30, 
        verbose_name    = "PLACE OF RECEIPT",
        blank           = True,
        null            = True,
    )
    place_of_delivery   = models.CharField(
        max_length      = 30, 
        verbose_name    = "PLACE OF DELIVERY",
        blank           = True,
        null            = True,
    )
    operator            = models.ForeignKey(
        branch_user,
        on_delete       = models.CASCADE,
        verbose_name    = 'OPERATOR',
        related_name    = "operator",
    )
    assistant           = models.ForeignKey(
        branch_user,
        on_delete       = models.CASCADE,
        verbose_name    = 'ASSISTANT',
        blank           = True,
        related_name    = "assistant",
        null            = True,
    )
    creator             = models.ForeignKey(
        branch_user,
        on_delete       = models.CASCADE,
        verbose_name    = 'CREATOR',
        blank           = True,
        related_name    = "creator",
    )
    update_date         = models.DateField(
        auto_now_add    = True,
        verbose_name    = 'UPDATE DATE',
    )

    def __str__(self):
        return self.job_no

class containersize(models.Model):
    containersize       = models.CharField(
        max_length      = 8,
        verbose_name    = "CNTR SIZE",
    )
    update_date         = models.DateField(
        auto_now_add    = True,
        verbose_name    = 'UPDATE DATE',
    )

    def __str__(self):
        return self.containersize

    def get_absolute_url(self):
        return reverse('containersizelist')

class container(models.Model):
    job_no              = models.ForeignKey(
        'job', 
        on_delete       = models.CASCADE,
        verbose_name    = 'JOB NO',
        blank           = True,
    )
    containerno         = models.CharField(
        max_length      = 14, 
        verbose_name    = "CONTAINER NO",

wenjian/templates/wenjian/clientlist.html
{% extends 'base.html' %}

{% block content %}
    <br />
    <div class="row">
        <div class="col-sm">
            <h4>CLIENT LIST</h4>
        </div>

        <div class="col-sm">
            <form method="POST" action="" class="form-inline my-2 my-lg-0">
                {% csrf_token %}
                {% for field in form %}
                    {{ field }}
                {% endfor %}
                <button type="submit" class="btn btn-outline-primary btn-sm" name="search_client">SEARCH</button>
            </form>
        </div>
        <div class="col-sm" style="text-align: right;">
            <a href="{% url 'client' %}" class="btn btn-outline-primary btn-sm" role="button">NEW</a>     
        </div>
    </div>

    <form method="POST" action = ''>{% csrf_token %}
    <table class="table table-sm table-hover">
        <tr class="table-active">
            <th>SELECT</th>
            <th>SHORT NAME</th>
            <th>FULL NAME</th>
            <th>TELEPHONE</th>
            <th>E-MAIL</th>
        </tr>
    {% for i in queryset %}
        <tr>
            <td><input type="checkbox" name='client_select' value='{{ i.id }}'></td>
            <td><a href="{% url 'clientupdate' i.id %}">{{ i.client_shortcut }}</a></td>
            <td>{{ i.client_name }}</td>
            <td>{{ i.client_tel}}</td>
            <td>{{ i.client_email }}</td>
        </tr>
    {% endfor %}  
    </table>
    {% include 'wenjian/html/pagination.html' %}
    </form>
{% endblock %}

wenjian/templates/wenjian/clientrole.html
{% extends 'base.html' %}

{% block cardhead %}
    {% include 'wenjian/html/cardclientrole.html' %}
{% endblock %}

{% block content %}
    <br />
    <h4>CLIENT ROLES</h4>
    <br />
    <form action="" method="post">
        {% csrf_token %}

        {% for ar in all_role %}
            {% if forloop.counter0|divisibleby:'3' %}
                <div class="form-group row">
            {% endif %}
            <div class="col-sm">
            {% if ar.id in client_role %}
                <input type="checkbox" name="role_select" value= '{{ ar.id }}' checked />
            {% else %}
                <input type="checkbox" name="role_select" value= '{{ ar.id }}'/>
            {% endif %}
            <label>{{ ar.role }}</label>
            </div>
            {% if forloop.counter|divisibleby:'3' %}
                </div>
            {% endif %}  
        {% endfor %}

        {% if c %}
            {% for count in c %}
                <div class="col-sm"></div>
            {% endfor %}
            </div>
        {% endif %}

        <div class="form-group row">
            <div class="col-sm-10">
                <button type="submit" class="btn btn-outline-primary btn-sm">SUBMIT</button>
            </div>
        </div>
    </form>
{% endblock %}

wenjian/templates/wenjian/contactlist.html
{% extends 'base.html' %}

{% block cardhead %}
    {% include 'wenjian/html/cardcontact.html' %}
{% endblock %}

{% block content %}
<br />
<div>
    <div style="float: left;">
        <h4>CONTACT PERSON LIST</h4>
    </div>
    <div style="text-align: right;">
        <a href="{% url 'contactadd' pk %}" class="btn btn-outline-primary btn-sm" role="button">NEW</a>
    </div>
</div>

<div style="margin-top: 20px;">
{% if contact_list %}
    <table class="table table-sm table-hover">
        <tr class="table-active">
            <th>PERSON NAME</th>
            <th>MOBILE PHONE</th>
            <th>E-MAIL</th>
        </tr>
    {% for p in contact_list %}
        <tr>
            <td><a href="{% url 'contactupdate' p.id %}">{{p.pic_name}}</a></td>
            <td>{{ p.pic_mobile }}</td>
            <td>{{ p.pic_email }}</td>          
        </tr>
    {% endfor %}
    </table>  
</div>
{% else %}
    <p>There is no DATA as well.</p>
{% endif %}
{% endblock %}

wenjian/templates/wenjian/containersize.html
{% extends 'base.html' %}

{% block cardhead %}
    {% include 'wenjian/html/cardcontainersize.html' %}
{% endblock %}

{% block content %}
    <br />
    <h4>CONTAINER SIZE</h4>
    <br />

    {% include 'wenjian/html/form.html' %}

{% endblock %}

wenjian/templates/wenjian/containersizelist.html
{% extends 'base.html' %}

{% block cardhead %}
    {% include 'wenjian/html/cardcontainersize.html' %}
{% endblock %}

{% block content %}
<br />
<div>
    <div style="float: left;">
        <h4>CONTAINER SIZE LIST</h4>
    </div>
    <div style="text-align: right;">
        <a href="{% url 'containersize' %}" class="btn btn-outline-primary btn-sm" role="button">NEW</a>
    </div>
</div>
<br />
{% if containersize_list %}
    {% for p in containersize_list %}
        {% if forloop.counter0|divisibleby:'5' %}
            <div class="row">
        {% endif %}
            <div class="col-sm">
                <a href="{% url 'containersizeupdate' p.id %}">{{p.containersize}}</a>
            </div>
        {% if forloop.counter|divisibleby:'5' %}
            </div>
        {% endif %}        
    {% endfor %} 
{% else %}
    <p>There is no DATA as well.</p>
{% endif %}
{% endblock %}

wenjian/templates/wenjian/currency.html
{% extends 'base.html' %}

{% block cardhead %}
    {% include 'wenjian/html/cardcurrency.html' %}
{% endblock %}

{% block content %}
    <br />
    <h4>CURRENCY</h4>
    <br />

    {% include 'wenjian/html/form.html' %}

{% endblock %}

wenjian/templates/wenjian/currencylist.html
{% extends 'base.html' %}

{% block cardhead %}
    {% include 'wenjian/html/cardcurrency.html' %}
{% endblock %}

{% block content %}
<br />
<div>
    <div style="float: left;">
        <h4>CURRENCY LIST</h4>
    </div>
    <div style="text-align: right;">
        <a href="{% url 'currency' %}" class="btn btn-outline-primary btn-sm" role="button">NEW</a>
    </div>
</div>

<div style="margin-top: 20px;">
{% if currency_list %}
    <table class="table table-sm table-hover">
        <tr class="table-active">
            <th>CURRENCY</th>
            <th>EXCHANGE RATE</th>
            <th>UPDATE DATE</th>
            <th>START DATE</th>
            <th>END DATE</th>
        </tr>
    {% for p in currency_list %}
        <tr>
            <td><a href="{% url 'currency_update' p.id %}">{{p.currency}}</a></td>
            <td>{{ p.exchangerate }}</td>
            <td>{{ p.updatedate|date:'Y-m-d' }}</td>
            <td>{{ p.startdate|date:'Y-m-d' }}</td>
            <td>{{ p.enddate|date:'Y-m-d' }}</td>            
        </tr>
    {% endfor %}
    </table>  
</div>
{% else %}
    <p>There is no DATA as well.</p>
{% endif %}
{% endblock %}

wenjian/templates/wenjian/expenselist.html
{% extends 'base.html' %}

{% block cardhead %}
    {% include 'wenjian/html/cardexpense.html' %}
{% endblock %}

{% block content %}
<br />
<div>
    <div style="float: left;">
        <h4>EXPENSE LIST</h4>
    </div>
    <div style="text-align: right;">
        <a href="{% url 'expense' %}" class="btn btn-outline-primary btn-sm" role="button">NEW</a>
    </div>
</div>
<br />
{% if expense_list %}
    {% for p in expense_list %}
        {% if forloop.counter0|divisibleby:'5' %}
            <div class="row">
        {% endif %}
            <div class="col-sm">
                <a href="{% url 'expenseupdate' p.id %}">{{p.expense}}</a>
            </div>
        {% if forloop.counter|divisibleby:'5' %}
            </div>
        {% endif %}        
    {% endfor %} 
{% else %}
    <p>There is no DATA as well.</p>
{% endif %}
{% endblock %}

wenjian/templates/wenjian/job.html
{% extends 'base.html' %}

{% block content %}
<h1>JOB</h1>

<form method="POST">
    {{ formset.management_form }}
    {% for form in formset %}
        {{ form }}
    {% endfor %}
    <input type='submit' value='Submit' class='btn btn-sm btn-outline-success' />
</form>

{% endblock %}

wenjian/templates/wenjian/office.html
{% extends 'base.html' %}

{% block cardhead %}
    {% include 'wenjian/html/cardoffice.html' %}
{% endblock %}

{% block content %}
    <br />
    <h4>BRANCH OFFICE</h4>
    <br />

    {% include 'wenjian/html/form.html' %}

{% endblock %}

wenjian/templates/wenjian/portlist.html
{% extends 'base.html' %}

{% block cardhead %}
    {% include 'wenjian/html/cardport.html' %}
{% endblock %}

{% block content %}
    <br />
    <div>
        <div style="float: left;">
            <h4>PORT LIST</h4>
        </div>
        <div style="text-align: right;">
            <a href="{% url 'port' %}" class="btn btn-outline-primary btn-sm" role="button">NEW</a>
        </div>
    </div>
    <br />
    {% if port_list %}
        {% for p in port_list %}
            {% if forloop.counter0|divisibleby:'5' %}
                <div class="row">
            {% endif %}
                <div class="col-sm">
                    <a href="{% url 'portupdate' p.id %}">{{p.port}}</a>
                </div>
            {% if forloop.counter|divisibleby:'5' %}
                </div>
            {% endif %}        
        {% endfor %} 
    {% else %}
        <p>There is no DATA as well.</p>
    {% endif %}
{% endblock %}

wenjian/templates/wenjian/rolelist.html
{% extends 'base.html' %}

{% block cardhead %}
    {% include 'wenjian/html/cardrole.html' %}
{% endblock %}

{% block content %}
<br />
<div>
    <div style="float: left;">
        <h4>ROLE LIST</h4>
    </div>
    <div style="text-align: right;">
        <a href="{% url 'role' %}" class="btn btn-outline-primary btn-sm" role="button">NEW</a>
    </div>
</div>
<br />
{% if role_list %}
    <table class="table, table-hover, table-sm">

    {% for p in role_list %}
        {% if forloop.counter0|divisibleby:'5' %}
            <tr>
        {% endif %}
            <td width="200px">
                <a href="{% url 'roleupdate' p.id %}">{{p.role}}</a>
            </td>
        {% if forloop.counter|divisibleby:'5' %}
            </tr>
        {% endif %}        
    {% endfor %}
    </tr>          
    </table> 
{% else %}
    <p>There is no DATA as well.</p>
{% endif %}
{% endblock %}

wenjian/templates/wenjian/user.html
{% extends 'base.html' %}

{% block cardhead %}
    {% include 'wenjian/html/carduser.html' %}
{% endblock %}

{% block content %}
    <br />
    <h4>USER</h4>
    <br />

    {% include 'wenjian/html/form.html' %}

{% endblock %}

wenjian/templates/wenjian/userlist.html
{% extends 'base.html' %}

{% block cardhead %}
    {% include 'wenjian/html/carduser.html' %}
{% endblock %}

{% block content %}
<br />
<div>
    <div style="float: left;">
        <h4>USER LIST</h4>
    </div>
    <div style="text-align: right;">
        <a href="{% url 'newuser' %}" class="btn btn-outline-primary btn-sm" role="button">NEW</a>
    </div>
</div>

<div style="margin-top: 20px;">
{% if user_list %}
    <table class="table table-sm table-hover">
        <tr class="table-active">
            <th>USER NAME       </th>
            <th>FIRST NAME      </th>
            <th>LAST NAME       </th>
            <th>BRANCH          </th>
            <th>E-MAIL          </th>
            <th>VALIDATE TO     </th>
            <th>PASSWORD</th>
        </tr>
    {% for p in user_list %}
        <tr>
            <td><a href="{% url 'updateuser' p.id %}">{{p.username}}</a></td>
            <td>{{ p.first_name }}      </td>
            <td>{{ p.last_name }}       </td>
            <td>{{ p.branch_office }}   </td>
            <td>{{ p.email }}           </td>
            <td>{{ p.validate_date }}   </td>
            <td><a href="{% url 'password' p.id %}">CHANGE</a>      </td>
        </tr>
    {% endfor %}
    </table>  
</div>
{% else %}
    <p>There is no DATA as well.</p>
{% endif %}
{% endblock %}